### ISSUE TITLE
[Question] Dimensions 

### ISSUE THREAD

**Issue by saahm** [maikmerten/hx8k-sram16-extension#2]
Hi, thanks for this and your other repository that offer these neat extension boards.
I wanted to roll my own HX8K breakout board extension and figured out the dimensions on the board a wildly mixed (inch and mm, plus sometimes there is no obvious reference by which some parts are placed there).
When I checked both your board designs I see that once the pin header are apart by 9.2128 mm and once by 9 mm for the same measurement. 
I currently can't accurately measure my ICE40HX8K-B-EVN board, but my estimate says 9.2128 is more correct, as 9 mm would be too little for that measurement.

I'm glad about your repos tho, it's the only available board for that breakout board I found so far that provide some useful references. 

I wanted to roll a board with all 4 headers on an extension board if possible, but from the breakout board itself I cant really figure out proper dimensions so far. Pretty undocumented, which is why your repos are an oasis in that regard :100: 

I thought to maybe bounce a few ideas here while asking that if you dont mind.

**Comment by maikmerten** [comment]
Yeah, the dimensions are somewhat "educated guesses" I made by crudely measuring my physical ICE40 boards, as I didn't find the original design files. The finished boards thankfully fit without needing persuasion - there's enough wiggle room in there. I accomplish this by inserting the header pins into the reference board, then putting the extension board on top and *then* soldering the headers into the extension board. This way sub-millimeter precision isn't crucial.

Between "hx8k-breakout-extension"  and "hx8k-sram16-extension", I'd assume the latter is more precise, as its a newer design.

Feel free to proceed with the designs as you see fit!

**Comment by saahm** [comment]
Ah, ok that explains a lot :) 
Thanks, so I will orient on your latest version.
